### ISSUE TITLE
@iconify/icons-mdi 1.2.0 breaks Jest test suite

### ISSUE THREAD

**Issue by torhovland** [iconify/icon-sets#34]
After I upgrade @iconify/icons-mdi from 1.1.47 to 1.2.0, Jest starts complaining:

```
 FAIL  src/Pages/Organization/__tests__/OrganizationView.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /frontend/node_modules/@iconify/icons-mdi/arrow-up.js:6
    export default data;
    ^^^^^^

    SyntaxError: Unexpected token 'export'

    > 1 | import arrowUpOutlined from '@iconify/icons-mdi/arrow-up';
        | ^
      2 | import openInNew from '@iconify/icons-mdi/open-in-new';
      3 | import { InlineIcon } from '@iconify/react';
      4 | import classNames from 'classnames';

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/Components/Link/Link.tsx:1:1)
```

**Comment by cyberalien** [comment]
Very sorry for this mess. It happened because of a typo in new script that updates icon sets. It generated ES modules for `@iconify/icons-*` packages and CJS for `@iconify-icons/*` packages, but its supposed to be other way around. Tests didn't notice bug because they can handle both ESM and CJS.

Thank you very much for reporting. Fixed.
